#!/usr/bin/env python3
"""
Real-grid sparse-sensor validation for condition-aware full-field recovery.

What this script does:
  1. Downloads real power-grid infrastructure from OpenStreetMap using Overpass.
  2. Builds a graph from OSM power lines/cables/minor lines.
  3. Downloads real historical weather from Open-Meteo for the grid centroid.
  4. Generates topology-aware operational response snapshots on the real grid.
  5. Performs sparse-sensor recovery using SVD, randomized SVD, CUR, and PDQ-style bases.
  6. Saves a compact evidence package of CSV tables and figures.

Important interpretation:
  This is public real-grid-topology validation, not proprietary utility SCADA validation.
  The network topology and weather are real public data. The node-level response fields
  are generated by a transparent graph-physics surrogate because public full-field voltage
  or loading measurements are usually unavailable.

Outputs:
  outdir/
    data/
      osm_power_elements.json
      grid_nodes.csv
      grid_edges.csv
      weather_hourly.csv
      snapshots.csv
    tables/
      raw_results.csv
      table_sensor_budget.csv
      table_noise.csv
      table_placement.csv
      summary_key_results.csv
    figures/
      real_grid_map.png
      real_grid_weather.png
      fig_sensor_budget_relerr.png
      fig_noise_relerr.png
      fig_placement_relerr.png
      fig_condition_vs_error.png
    manifest.json

Dependencies:
  numpy, pandas, scipy, matplotlib, requests, networkx
"""

from __future__ import annotations

import argparse
import json
import math
import time
from dataclasses import dataclass, asdict
from pathlib import Path
from typing import Dict, List, Tuple, Optional, Any

import numpy as np
import pandas as pd
import requests
import networkx as nx
import matplotlib.pyplot as plt

from scipy.linalg import qr
from scipy.sparse import csr_matrix, diags
from scipy.sparse.linalg import spsolve


# ============================================================
# Configuration
# ============================================================

@dataclass
class Config:
    seed: int = 123

    place: str = "Kampala, Uganda"
    bbox: Optional[Tuple[float, float, float, float]] = None
    # bbox format: north, west, south, east

    start_date: str = "2024-01-01"
    end_date: str = "2024-01-21"

    rank: int = 10
    max_nodes: int = 450
    min_nodes_required: int = 20

    train_frac: float = 0.60
    val_frac: float = 0.20

    sensor_budgets: Tuple[float, ...] = (0.05, 0.10, 0.20, 0.40)
    noise_levels: Tuple[float, ...] = (0.0, 0.01, 0.05, 0.10, 0.20)
    placement_modes: Tuple[str, ...] = ("random", "leverage", "qr", "degree", "poor")

    gamma_multipliers: Tuple[float, ...] = (
        0.0,
        1e-10,
        1e-8,
        1e-6,
        1e-4,
        1e-2,
        1e-1,
        1.0,
    )

    n_trials: int = 5
    pdq_kappa_max: float = 50.0
    ridge_eps: float = 1e-12

    overpass_url: str = "https://overpass-api.de/api/interpreter"
    nominatim_url: str = "https://nominatim.openstreetmap.org/search"
    open_meteo_url: str = "https://archive-api.open-meteo.com/v1/archive"

    user_agent: str = "SparseSensorDigitalTwinResearch/1.0"


# ============================================================
# Basic utilities
# ============================================================

def safe_mkdir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def set_seed(seed: int) -> np.random.Generator:
    return np.random.default_rng(seed)


def http_get_json(url: str, params: Dict[str, Any], user_agent: str, timeout: int = 90) -> Any:
    headers = {"User-Agent": user_agent}
    r = requests.get(url, params=params, headers=headers, timeout=timeout)
    r.raise_for_status()
    return r.json()


def http_post_text(url: str, data: str, user_agent: str, timeout: int = 180) -> Any:
    headers = {"User-Agent": user_agent}
    r = requests.post(url, data={"data": data}, headers=headers, timeout=timeout)
    r.raise_for_status()
    return r.json()


def haversine_km(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    radius = 6371.0088
    p1 = math.radians(lat1)
    p2 = math.radians(lat2)
    dp = math.radians(lat2 - lat1)
    dl = math.radians(lon2 - lon1)
    a = math.sin(dp / 2) ** 2 + math.cos(p1) * math.cos(p2) * math.sin(dl / 2) ** 2
    return 2 * radius * math.asin(math.sqrt(a))


def relative_noise(x: np.ndarray, level: float, rng: np.random.Generator) -> np.ndarray:
    if level <= 0:
        return np.zeros_like(x)
    eta = rng.standard_normal(size=x.shape)
    eta_norm = np.linalg.norm(eta)
    x_norm = max(np.linalg.norm(x), 1e-14)
    if eta_norm < 1e-14:
        return np.zeros_like(x)
    return eta / eta_norm * (level * x_norm)


def condition_number_from_svals(svals: np.ndarray, eps: float = 1e-14) -> float:
    if len(svals) == 0:
        return float("inf")
    smax = float(np.max(svals))
    smin = float(np.min(svals))
    if smin <= eps:
        return float("inf")
    return smax / smin


def finite_or_nan(x: float) -> float:
    return float(x) if np.isfinite(x) else np.nan


# ============================================================
# Geocoding and OSM download
# ============================================================

def geocode_place(place: str, cfg: Config) -> Tuple[float, float, float, float, float, float]:
    """
    Returns north, west, south, east, lat, lon.
    """
    params = {
        "q": place,
        "format": "json",
        "limit": 1,
        "polygon_geojson": 0,
    }
    data = http_get_json(cfg.nominatim_url, params=params, user_agent=cfg.user_agent, timeout=60)
    if not data:
        raise RuntimeError(f"Could not geocode place: {place}")

    item = data[0]
    south, north, west, east = [float(v) for v in item["boundingbox"]]
    lat = float(item["lat"])
    lon = float(item["lon"])

    return north, west, south, east, lat, lon


def build_overpass_query(north: float, west: float, south: float, east: float) -> str:
    """
    Download power ways and nodes inside bounding box.
    We include line, minor_line, cable, substation, transformer, tower, pole.
    """
    bbox = f"{south},{west},{north},{east}"
    query = f"""
    [out:json][timeout:120];
    (
      way["power"~"^(line|minor_line|cable)$"]({bbox});
      node["power"~"^(substation|transformer|tower|pole)$"]({bbox});
      way["power"="substation"]({bbox});
      relation["power"="substation"]({bbox});
    );
    (._;>;);
    out body;
    """
    return query


def download_osm_power(cfg: Config, out_json: Path) -> Dict[str, Any]:
    if cfg.bbox is not None:
        north, west, south, east = cfg.bbox
        lat = 0.5 * (north + south)
        lon = 0.5 * (west + east)
    else:
        north, west, south, east, lat, lon = geocode_place(cfg.place, cfg)

    query = build_overpass_query(north, west, south, east)
    data = http_post_text(cfg.overpass_url, query, user_agent=cfg.user_agent, timeout=180)

    payload = {
        "place": cfg.place,
        "bbox": {"north": north, "west": west, "south": south, "east": east},
        "centroid": {"lat": lat, "lon": lon},
        "overpass_query": query,
        "osm_data": data,
    }

    with open(out_json, "w", encoding="utf-8") as f:
        json.dump(payload, f)

    return payload


# ============================================================
# Build grid graph from OSM
# ============================================================

def parse_osm_power_graph(payload: Dict[str, Any], cfg: Config) -> Tuple[nx.Graph, pd.DataFrame, pd.DataFrame]:
    elements = payload["osm_data"].get("elements", [])

    osm_nodes: Dict[int, Tuple[float, float, Dict[str, Any]]] = {}
    ways: List[Dict[str, Any]] = []

    for el in elements:
        if el.get("type") == "node" and "lat" in el and "lon" in el:
            osm_nodes[int(el["id"])] = (
                float(el["lat"]),
                float(el["lon"]),
                el.get("tags", {}),
            )
        elif el.get("type") == "way" and "nodes" in el:
            tags = el.get("tags", {})
            if tags.get("power") in {"line", "minor_line", "cable", "substation"}:
                ways.append(el)

    G = nx.Graph()

    # Add all nodes referenced by line/cable ways.
    for way in ways:
        ptype = way.get("tags", {}).get("power", "")
        if ptype not in {"line", "minor_line", "cable"}:
            continue
        node_ids = [int(v) for v in way.get("nodes", []) if int(v) in osm_nodes]
        for nid in node_ids:
            lat, lon, tags = osm_nodes[nid]
            G.add_node(nid, lat=lat, lon=lon, tags=tags, power=tags.get("power", ""))
        for a, b in zip(node_ids[:-1], node_ids[1:]):
            if a == b:
                continue
            lat1, lon1, _ = osm_nodes[a]
            lat2, lon2, _ = osm_nodes[b]
            length_km = haversine_km(lat1, lon1, lat2, lon2)
            if length_km <= 0:
                continue
            voltage = way.get("tags", {}).get("voltage", "")
            G.add_edge(
                a,
                b,
                length_km=length_km,
                power=ptype,
                voltage=voltage,
                osm_way_id=way.get("id"),
            )

    if G.number_of_nodes() == 0 or G.number_of_edges() == 0:
        raise RuntimeError(
            "No usable OSM power-line graph was found. Try a larger bbox or a different place."
        )

    # Keep largest connected component.
    components = sorted(nx.connected_components(G), key=len, reverse=True)
    G = G.subgraph(components[0]).copy()

    # Limit size for quick reproducible experiments.
    if G.number_of_nodes() > cfg.max_nodes:
        # Keep high-degree/geographically central component subset by BFS from max-degree node.
        degrees = dict(G.degree())
        start = max(degrees, key=degrees.get)
        chosen = []
        seen = {start}
        queue = [start]
        while queue and len(chosen) < cfg.max_nodes:
            u = queue.pop(0)
            chosen.append(u)
            neigh = sorted(G.neighbors(u), key=lambda v: degrees.get(v, 0), reverse=True)
            for v in neigh:
                if v not in seen:
                    seen.add(v)
                    queue.append(v)
        G = G.subgraph(chosen).copy()

    if G.number_of_nodes() < cfg.min_nodes_required:
        raise RuntimeError(
            f"Only {G.number_of_nodes()} grid nodes found. Need at least {cfg.min_nodes_required}. "
            "Try a larger bbox or another city/region."
        )

    # Relabel nodes to compact integer ids.
    mapping = {old: i for i, old in enumerate(G.nodes())}
    old_ids = {i: old for old, i in mapping.items()}
    G2 = nx.relabel_nodes(G, mapping, copy=True)
    nx.set_node_attributes(G2, old_ids, "osm_id")

    node_rows = []
    for i, data in G2.nodes(data=True):
        node_rows.append({
            "node": i,
            "osm_id": data.get("osm_id"),
            "lat": data.get("lat"),
            "lon": data.get("lon"),
            "power": data.get("power", ""),
            "degree": int(G2.degree(i)),
        })
    nodes_df = pd.DataFrame(node_rows).sort_values("node")

    edge_rows = []
    for u, v, data in G2.edges(data=True):
        edge_rows.append({
            "u": int(u),
            "v": int(v),
            "length_km": float(data.get("length_km", np.nan)),
            "power": data.get("power", ""),
            "voltage": data.get("voltage", ""),
            "osm_way_id": data.get("osm_way_id", ""),
        })
    edges_df = pd.DataFrame(edge_rows)

    return G2, nodes_df, edges_df


def graph_laplacian_conductance(G: nx.Graph) -> csr_matrix:
    n = G.number_of_nodes()
    rows, cols, data = [], [], []

    conductance = {}
    for u, v, d in G.edges(data=True):
        length = max(float(d.get("length_km", 1.0)), 1e-3)
        c = 1.0 / length
        conductance[(u, v)] = c
        conductance[(v, u)] = c

    diag = np.zeros(n)
    for u, v in G.edges():
        c = conductance[(u, v)]
        diag[u] += c
        diag[v] += c
        rows.extend([u, v])
        cols.extend([v, u])
        data.extend([-c, -c])

    rows.extend(range(n))
    cols.extend(range(n))
    data.extend(diag)

    L = csr_matrix((data, (rows, cols)), shape=(n, n))
    return L


# ============================================================
# Weather download and response snapshots
# ============================================================

def download_weather(lat: float, lon: float, cfg: Config, out_csv: Path) -> pd.DataFrame:
    params = {
        "latitude": lat,
        "longitude": lon,
        "start_date": cfg.start_date,
        "end_date": cfg.end_date,
        "hourly": "temperature_2m,relative_humidity_2m,precipitation,wind_speed_10m,shortwave_radiation",
        "timezone": "auto",
    }

    data = http_get_json(cfg.open_meteo_url, params=params, user_agent=cfg.user_agent, timeout=90)

    hourly = data.get("hourly", {})
    if not hourly or "time" not in hourly:
        raise RuntimeError("Open-Meteo response did not contain hourly weather data.")

    df = pd.DataFrame(hourly)
    df.to_csv(out_csv, index=False)
    return df


def node_spatial_weights(nodes_df: pd.DataFrame, rng: np.random.Generator) -> np.ndarray:
    """
    Create fixed node-level demand weights from coordinates and degree.
    This is a transparent public-data proxy, not utility demand data.
    """
    lat = nodes_df["lat"].to_numpy(dtype=float)
    lon = nodes_df["lon"].to_numpy(dtype=float)
    degree = nodes_df["degree"].to_numpy(dtype=float)

    latn = (lat - np.nanmean(lat)) / (np.nanstd(lat) + 1e-12)
    lonn = (lon - np.nanmean(lon)) / (np.nanstd(lon) + 1e-12)

    base = 1.0 + 0.25 * degree + 0.15 * np.sin(2.0 * latn) + 0.15 * np.cos(2.0 * lonn)
    jitter = 0.08 * rng.standard_normal(size=len(base))
    w = np.maximum(base + jitter, 0.05)
    w = w / np.mean(w)
    return w


def generate_grid_response_snapshots(
    G: nx.Graph,
    nodes_df: pd.DataFrame,
    weather: pd.DataFrame,
    cfg: Config,
    rng: np.random.Generator,
) -> pd.DataFrame:
    """
    Generate operational response snapshots on the real OSM grid topology.

    Model:
      q_t = node injections influenced by real weather and hour-of-day.
      v_t solves (L + rho I) v = q_t with graph smoothing.
      response_t combines v_t with local normalized load.

    Interpretation:
      The topology and weather are real. The response is a transparent
      graph-physics surrogate for public validation when SCADA/full-field
      node measurements are unavailable.
    """
    n = G.number_of_nodes()
    L = graph_laplacian_conductance(G)

    rho = 0.08
    Aop = L + rho * diags(np.ones(n), 0, format="csr")

    w_node = node_spatial_weights(nodes_df, rng)

    df = weather.copy()
    df["time"] = pd.to_datetime(df["time"])
    hours = df["time"].dt.hour.to_numpy()

    temp = df["temperature_2m"].to_numpy(dtype=float)
    wind = df["wind_speed_10m"].to_numpy(dtype=float)
    rad = df["shortwave_radiation"].to_numpy(dtype=float)
    precip = df["precipitation"].to_numpy(dtype=float)

    temp_z = (temp - np.nanmean(temp)) / (np.nanstd(temp) + 1e-12)
    wind_z = (wind - np.nanmean(wind)) / (np.nanstd(wind) + 1e-12)
    rad_z = (rad - np.nanmean(rad)) / (np.nanstd(rad) + 1e-12)
    precip_z = (precip - np.nanmean(precip)) / (np.nanstd(precip) + 1e-12)

    # Demand-like daily profile
    daily = (
        1.0
        + 0.20 * np.sin(2 * np.pi * (hours - 7) / 24.0)
        + 0.15 * np.sin(2 * np.pi * (hours - 18) / 24.0)
    )

    # Weather-modulated demand and renewable-like stress terms
    system_driver = (
        daily
        + 0.12 * temp_z
        + 0.08 * wind_z
        - 0.10 * rad_z
        + 0.04 * precip_z
    )

    X = np.zeros((n, len(df)), dtype=float)

    for t in range(len(df)):
        spatial_wave = 0.05 * np.sin(0.2 * np.arange(n) + 0.1 * t)
        q = system_driver[t] * w_node + spatial_wave
        q = q - np.mean(q)
        q += 0.01 * rng.standard_normal(n)

        v = spsolve(Aop, q)
        v = np.asarray(v)
        v = (v - np.mean(v)) / (np.std(v) + 1e-12)

        # A public-data proxy response, analogous to normalized voltage/stress field.
        response = 0.75 * v + 0.25 * (q - np.mean(q)) / (np.std(q) + 1e-12)
        X[:, t] = response

    snap = pd.DataFrame(X, columns=[f"t_{i:04d}" for i in range(X.shape[1])])
    snap.insert(0, "node", np.arange(n))
    return snap


# ============================================================
# Bases
# ============================================================

def svd_basis(A: np.ndarray, r: int) -> np.ndarray:
    U, _, _ = np.linalg.svd(A, full_matrices=False)
    return U[:, :r]


def randomized_svd_basis(A: np.ndarray, r: int, rng: np.random.Generator, oversample: int = 8, n_iter: int = 1) -> np.ndarray:
    n, m = A.shape
    ell = min(r + oversample, min(n, m))
    Omega = rng.standard_normal(size=(m, ell))
    Y = A @ Omega
    for _ in range(n_iter):
        Y = A @ (A.T @ Y)
    Q, _ = np.linalg.qr(Y, mode="reduced")
    Bsmall = Q.T @ A
    Usmall, _, _ = np.linalg.svd(Bsmall, full_matrices=False)
    U = Q @ Usmall
    return U[:, :r]


def cur_column_basis(A: np.ndarray, r: int) -> np.ndarray:
    U, _, Vt = np.linalg.svd(A, full_matrices=False)
    rr = min(r, Vt.shape[0])
    lev = np.sum(Vt[:rr, :] ** 2, axis=0)
    chosen = np.argsort(lev)[::-1][:r]
    C = A[:, chosen]
    Q, R = np.linalg.qr(C, mode="reduced")
    if Q.shape[1] < r or np.linalg.matrix_rank(R) < min(R.shape):
        return U[:, :r]
    return Q[:, :r]


def pdq_condition_aware_basis(A: np.ndarray, r: int, kappa_max: float = 50.0, eps: float = 1e-12) -> Tuple[np.ndarray, Dict[str, float]]:
    U, s, _ = np.linalg.svd(A, full_matrices=False)
    U = U[:, :r]
    s = s[:r]
    smax = max(float(s[0]), eps)
    floor = smax / max(kappa_max, 1.0)
    d = np.sqrt(np.maximum(s, floor))
    B = U * d.reshape(1, -1)
    return B, {
        "pdq_core_kappa": float(np.max(d) / max(np.min(d), eps)),
        "pdq_core_min": float(np.min(d)),
        "pdq_core_max": float(np.max(d)),
    }


def fit_bases(A_train: np.ndarray, cfg: Config, rng: np.random.Generator) -> Dict[str, Dict[str, Any]]:
    bases: Dict[str, Dict[str, Any]] = {}

    t0 = time.perf_counter()
    bases["SVD"] = {"B": svd_basis(A_train, cfg.rank), "fit_time": time.perf_counter() - t0, "diagnostics": {}}

    t0 = time.perf_counter()
    bases["rSVD"] = {"B": randomized_svd_basis(A_train, cfg.rank, rng), "fit_time": time.perf_counter() - t0, "diagnostics": {}}

    t0 = time.perf_counter()
    bases["CUR"] = {"B": cur_column_basis(A_train, cfg.rank), "fit_time": time.perf_counter() - t0, "diagnostics": {}}

    t0 = time.perf_counter()
    Bpdq, diag = pdq_condition_aware_basis(A_train, cfg.rank, cfg.pdq_kappa_max)
    bases["PDQ"] = {"B": Bpdq, "fit_time": time.perf_counter() - t0, "diagnostics": diag}

    return bases


# ============================================================
# Sensor selection and recovery
# ============================================================

def select_sensors(B: np.ndarray, s: int, mode: str, rng: np.random.Generator, nodes_df: pd.DataFrame) -> np.ndarray:
    n = B.shape[0]
    s = max(1, min(int(s), n))

    lev = np.sum(B ** 2, axis=1)
    degree = nodes_df["degree"].to_numpy(dtype=float)

    if mode == "random":
        return np.sort(rng.choice(n, size=s, replace=False))

    if mode == "leverage":
        return np.sort(np.argsort(lev)[::-1][:s])

    if mode == "poor":
        return np.sort(np.argsort(lev)[:s])

    if mode == "degree":
        score = degree + 0.05 * lev / (np.max(lev) + 1e-12)
        return np.sort(np.argsort(score)[::-1][:s])

    if mode == "qr":
        try:
            _, _, piv = qr(B.T, pivoting=True, mode="economic")
            return np.sort(piv[:s])
        except Exception:
            return np.sort(np.argsort(lev)[::-1][:s])

    raise ValueError(f"Unknown placement mode: {mode}")


def recover(B: np.ndarray, x: np.ndarray, idx: np.ndarray, gamma: float, noise_level: float, rng: np.random.Generator, ridge_eps: float = 1e-12) -> Tuple[np.ndarray, Dict[str, float]]:
    G = B[idx, :]
    y_clean = x[idx]
    eta = relative_noise(y_clean, noise_level, rng)
    y = y_clean + eta

    r = B.shape[1]
    H = G.T @ G + gamma * np.eye(r)
    b = G.T @ y

    t0 = time.perf_counter()
    try:
        if gamma > 0:
            zhat = np.linalg.solve(H, b)
        else:
            zhat, *_ = np.linalg.lstsq(G, y, rcond=None)
    except np.linalg.LinAlgError:
        zhat = np.linalg.pinv(H + ridge_eps * np.eye(r)) @ b
    online_time = time.perf_counter() - t0

    xhat = B @ zhat

    svals = np.linalg.svd(G, compute_uv=False)
    if len(svals) < r:
        sigma_min = 0.0
    else:
        sigma_min = float(np.min(svals))
    sigma_max = float(np.max(svals)) if len(svals) else 0.0

    svals_full = np.concatenate([svals, np.zeros(max(0, r - len(svals)))])
    kappa = condition_number_from_svals(svals_full)

    try:
        amp_mat = np.linalg.solve(H + ridge_eps * np.eye(r), G.T)
        amplification = float(np.linalg.norm(B, 2) * np.linalg.norm(amp_mat, 2))
    except Exception:
        amplification = np.nan

    return xhat, {
        "noise_norm": float(np.linalg.norm(eta)),
        "sigma_min_SB": finite_or_nan(sigma_min),
        "sigma_max_SB": finite_or_nan(sigma_max),
        "kappa_SB": finite_or_nan(kappa),
        "amplification": finite_or_nan(amplification),
        "online_time_sec": float(online_time),
        "n_sensors_used": int(len(idx)),
    }


def basis_error(B: np.ndarray, x: np.ndarray) -> float:
    try:
        z, *_ = np.linalg.lstsq(B, x, rcond=None)
        xp = B @ z
    except Exception:
        xp = B @ (np.linalg.pinv(B) @ x)
    return float(np.linalg.norm(x - xp) / max(np.linalg.norm(x), 1e-14))


def metrics(x: np.ndarray, xhat: np.ndarray, L: Optional[csr_matrix] = None) -> Dict[str, float]:
    d = xhat - x
    rel = np.linalg.norm(d) / max(np.linalg.norm(x), 1e-14)
    maxerr = np.max(np.abs(d))
    if L is not None:
        num = float(d.T @ (L @ d))
        den = float(x.T @ (L @ x))
        energy = math.sqrt(max(num, 0.0)) / max(math.sqrt(max(den, 0.0)), 1e-14)
    else:
        energy = np.nan
    return {"RelErr": float(rel), "MaxErr": float(maxerr), "EnergyErr": float(energy)}


def choose_gamma(B: np.ndarray, X_val: np.ndarray, idx: np.ndarray, noise_level: float, cfg: Config) -> float:
    G = B[idx, :]
    scale = float(np.trace(G.T @ G) / max(B.shape[1], 1))
    scale = max(scale, 1e-12)

    best_gamma = None
    best_score = np.inf

    local_rng = np.random.default_rng(777)
    for mult in cfg.gamma_multipliers:
        gamma = float(mult * scale)
        errs = []
        for j in range(X_val.shape[1]):
            x = X_val[:, j]
            xhat, _ = recover(B, x, idx, gamma, noise_level, local_rng, cfg.ridge_eps)
            errs.append(metrics(x, xhat)["RelErr"])
        score = float(np.mean(errs))
        if score < best_score:
            best_score = score
            best_gamma = gamma

    return float(best_gamma if best_gamma is not None else 1e-8)


# ============================================================
# Experiments
# ============================================================

def split_snapshots(X: np.ndarray, cfg: Config) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    m = X.shape[1]
    n_train = int(cfg.train_frac * m)
    n_val = int(cfg.val_frac * m)
    if n_train < 10 or n_val < 5 or m - n_train - n_val < 5:
        raise RuntimeError("Not enough weather/snapshot time points. Use a wider date range.")
    return X[:, :n_train], X[:, n_train:n_train + n_val], X[:, n_train + n_val:]


def evaluate(
    *,
    experiment: str,
    method: str,
    B: np.ndarray,
    fit_time: float,
    X_test: np.ndarray,
    X_val: np.ndarray,
    L: csr_matrix,
    nodes_df: pd.DataFrame,
    sensor_budget: float,
    noise_level: float,
    placement: str,
    cfg: Config,
    rng: np.random.Generator,
    trial: int,
) -> List[Dict[str, Any]]:
    n = B.shape[0]
    s = max(1, int(round(sensor_budget * n)))
    idx = select_sensors(B, s, placement, rng, nodes_df)
    gamma = choose_gamma(B, X_val, idx, noise_level, cfg)

    rows = []
    for j in range(X_test.shape[1]):
        x = X_test[:, j]
        xhat, diag = recover(B, x, idx, gamma, noise_level, rng, cfg.ridge_eps)
        row = {
            "experiment": experiment,
            "method": method,
            "sensor_budget": float(sensor_budget),
            "noise_level": float(noise_level),
            "placement": placement,
            "trial": int(trial),
            "snapshot_id": int(j),
            "gamma": float(gamma),
            "fit_time_sec": float(fit_time),
            "BasisErr": basis_error(B, x),
            **metrics(x, xhat, L),
            **diag,
        }
        rows.append(row)
    return rows


def run_validation(cfg: Config, outdir: Path) -> None:
    rng = set_seed(cfg.seed)

    data_dir = outdir / "data"
    tables_dir = outdir / "tables"
    figures_dir = outdir / "figures"
    for p in (data_dir, tables_dir, figures_dir):
        safe_mkdir(p)

    print("[1/7] Downloading real OSM power-grid infrastructure...")
    osm_payload = download_osm_power(cfg, data_dir / "osm_power_elements.json")

    print("[2/7] Building real grid graph...")
    G, nodes_df, edges_df = parse_osm_power_graph(osm_payload, cfg)
    nodes_df.to_csv(data_dir / "grid_nodes.csv", index=False)
    edges_df.to_csv(data_dir / "grid_edges.csv", index=False)

    centroid_lat = float(nodes_df["lat"].mean())
    centroid_lon = float(nodes_df["lon"].mean())

    print("[3/7] Downloading real historical weather...")
    weather = download_weather(centroid_lat, centroid_lon, cfg, data_dir / "weather_hourly.csv")

    print("[4/7] Generating topology-aware response snapshots on the real grid...")
    snapshots_df = generate_grid_response_snapshots(G, nodes_df, weather, cfg, rng)
    snapshots_df.to_csv(data_dir / "snapshots.csv", index=False)

    X = snapshots_df.drop(columns=["node"]).to_numpy(dtype=float)
    X_train, X_val, X_test = split_snapshots(X, cfg)

    # Remove temporal mean learned from train.
    mean_train = X_train.mean(axis=1, keepdims=True)
    X_train = X_train - mean_train
    X_val = X_val - mean_train
    X_test = X_test - mean_train

    L = graph_laplacian_conductance(G)

    print("[5/7] Fitting bases...")
    bases = fit_bases(X_train, cfg, rng)

    print("[6/7] Running real-data validation experiments...")
    rows: List[Dict[str, Any]] = []

    # Experiment 1: sensor budget
    for method, item in bases.items():
        for budget in cfg.sensor_budgets:
            for trial in range(cfg.n_trials):
                rows.extend(evaluate(
                    experiment="sensor_budget",
                    method=method,
                    B=item["B"],
                    fit_time=item["fit_time"],
                    X_test=X_test,
                    X_val=X_val,
                    L=L,
                    nodes_df=nodes_df,
                    sensor_budget=budget,
                    noise_level=0.05,
                    placement="qr",
                    cfg=cfg,
                    rng=np.random.default_rng(cfg.seed + 1000 + trial),
                    trial=trial,
                ))

    # Experiment 2: sensor noise
    for method, item in bases.items():
        for noise in cfg.noise_levels:
            rows.extend(evaluate(
                experiment="noise",
                method=method,
                B=item["B"],
                fit_time=item["fit_time"],
                X_test=X_test,
                X_val=X_val,
                L=L,
                nodes_df=nodes_df,
                sensor_budget=0.20,
                noise_level=noise,
                placement="qr",
                cfg=cfg,
                rng=np.random.default_rng(cfg.seed + 2000 + int(noise * 1000)),
                trial=0,
            ))

    # Experiment 3: sensor placement
    for method, item in bases.items():
        for placement in cfg.placement_modes:
            for trial in range(cfg.n_trials):
                rows.extend(evaluate(
                    experiment="placement",
                    method=method,
                    B=item["B"],
                    fit_time=item["fit_time"],
                    X_test=X_test,
                    X_val=X_val,
                    L=L,
                    nodes_df=nodes_df,
                    sensor_budget=0.20,
                    noise_level=0.05,
                    placement=placement,
                    cfg=cfg,
                    rng=np.random.default_rng(cfg.seed + 3000 + trial),
                    trial=trial,
                ))

    df = pd.DataFrame(rows)
    for method, item in bases.items():
        for key, value in item.get("diagnostics", {}).items():
            df.loc[df["method"] == method, key] = value

    raw_path = tables_dir / "raw_results.csv"
    df.to_csv(raw_path, index=False)

    print("[7/7] Saving tables and figures...")
    save_tables_and_figures(
        df=df,
        G=G,
        nodes_df=nodes_df,
        edges_df=edges_df,
        weather=weather,
        tables_dir=tables_dir,
        figures_dir=figures_dir,
    )

    manifest = {
        "config": asdict(cfg),
        "place": cfg.place,
        "bbox": osm_payload["bbox"],
        "centroid": {"lat": centroid_lat, "lon": centroid_lon},
        "n_grid_nodes": int(G.number_of_nodes()),
        "n_grid_edges": int(G.number_of_edges()),
        "n_weather_hours": int(len(weather)),
        "methods": list(bases.keys()),
        "interpretation": [
            "OSM power topology and Open-Meteo weather are real public data.",
            "Node-level response fields are generated by a transparent graph-physics surrogate.",
            "This validates sparse-sensor recovery on real infrastructure topology, not proprietary SCADA measurements.",
        ],
    }
    with open(outdir / "manifest.json", "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2)

    print("\nDone.")
    print(f"Grid nodes: {G.number_of_nodes()}, edges: {G.number_of_edges()}")
    print(f"Outputs saved to: {outdir}")


# ============================================================
# Tables and figures
# ============================================================

def aggregate(df: pd.DataFrame, group_cols: List[str]) -> pd.DataFrame:
    cols = [
        "RelErr",
        "MaxErr",
        "EnergyErr",
        "BasisErr",
        "sigma_min_SB",
        "kappa_SB",
        "amplification",
        "online_time_sec",
        "fit_time_sec",
        "gamma",
        "n_sensors_used",
    ]
    out = df.groupby(group_cols)[cols].agg(["mean", "std", "median"]).reset_index()
    out.columns = [
        "_".join([str(x) for x in c if str(x) != ""]).rstrip("_")
        for c in out.columns
    ]
    return out


def save_tables_and_figures(
    df: pd.DataFrame,
    G: nx.Graph,
    nodes_df: pd.DataFrame,
    edges_df: pd.DataFrame,
    weather: pd.DataFrame,
    tables_dir: Path,
    figures_dir: Path,
) -> None:
    raw_specs = {
        "table_sensor_budget.csv": (df[df["experiment"] == "sensor_budget"], ["experiment", "method", "sensor_budget"]),
        "table_noise.csv": (df[df["experiment"] == "noise"], ["experiment", "method", "noise_level"]),
        "table_placement.csv": (df[df["experiment"] == "placement"], ["experiment", "method", "placement"]),
    }

    for name, (sub, group_cols) in raw_specs.items():
        aggregate(sub, group_cols).to_csv(tables_dir / name, index=False)

    summary = df.groupby(["experiment", "method"]).agg(
        RelErr_mean=("RelErr", "mean"),
        EnergyErr_mean=("EnergyErr", "mean"),
        kappa_SB_median=("kappa_SB", "median"),
        amplification_median=("amplification", "median"),
        online_time_mean=("online_time_sec", "mean"),
    ).reset_index()
    summary.to_csv(tables_dir / "summary_key_results.csv", index=False)

    plot_grid(G, nodes_df, edges_df, figures_dir / "real_grid_map.png")
    plot_weather(weather, figures_dir / "real_grid_weather.png")

    table_budget = pd.read_csv(tables_dir / "table_sensor_budget.csv")
    plot_lines(table_budget, "sensor_budget", "RelErr_mean", "method",
               "Sensor budget s/n", "Mean relative recovery error",
               "Real-grid recovery versus sensor budget",
               figures_dir / "fig_sensor_budget_relerr.png")

    table_noise = pd.read_csv(tables_dir / "table_noise.csv")
    plot_lines(table_noise, "noise_level", "RelErr_mean", "method",
               "Relative sensor noise", "Mean relative recovery error",
               "Real-grid noise robustness",
               figures_dir / "fig_noise_relerr.png")

    table_place = pd.read_csv(tables_dir / "table_placement.csv")
    plot_placement(table_place, figures_dir / "fig_placement_relerr.png")

    plot_condition_vs_error(df, figures_dir / "fig_condition_vs_error.png")


def plot_grid(G: nx.Graph, nodes_df: pd.DataFrame, edges_df: pd.DataFrame, outpath: Path) -> None:
    pos = {int(r.node): (float(r.lon), float(r.lat)) for r in nodes_df.itertuples()}
    plt.figure(figsize=(7.2, 7.2))
    for u, v in G.edges():
        x1, y1 = pos[u]
        x2, y2 = pos[v]
        plt.plot([x1, x2], [y1, y2], linewidth=0.7, alpha=0.65)
    deg = nodes_df["degree"].to_numpy()
    plt.scatter(nodes_df["lon"], nodes_df["lat"], s=8 + 6 * deg, alpha=0.85)
    plt.xlabel("Longitude")
    plt.ylabel("Latitude")
    plt.title("Real OpenStreetMap power-grid topology used for validation")
    plt.grid(True, alpha=0.25)
    plt.tight_layout()
    plt.savefig(outpath, dpi=300)
    plt.close()


def plot_weather(weather: pd.DataFrame, outpath: Path) -> None:
    df = weather.copy()
    df["time"] = pd.to_datetime(df["time"])
    plt.figure(figsize=(8.4, 4.6))
    plt.plot(df["time"], df["temperature_2m"], label="Temperature 2m")
    if "shortwave_radiation" in df:
        rad = df["shortwave_radiation"].to_numpy(dtype=float)
        rad_scaled = (rad - np.nanmin(rad)) / (np.nanmax(rad) - np.nanmin(rad) + 1e-12)
        temp = df["temperature_2m"].to_numpy(dtype=float)
        rad_scaled = rad_scaled * (np.nanmax(temp) - np.nanmin(temp)) + np.nanmin(temp)
        plt.plot(df["time"], rad_scaled, label="Shortwave radiation, scaled")
    plt.xlabel("Time")
    plt.ylabel("Weather signal")
    plt.title("Downloaded real weather used as operational driver")
    plt.legend(frameon=False)
    plt.grid(True, alpha=0.25)
    plt.tight_layout()
    plt.savefig(outpath, dpi=300)
    plt.close()


def plot_lines(table: pd.DataFrame, x_col: str, y_col: str, group_col: str, xlabel: str, ylabel: str, title: str, outpath: Path) -> None:
    plt.figure(figsize=(7.2, 4.6))
    for method, sub in table.groupby(group_col):
        sub = sub.sort_values(x_col)
        plt.plot(sub[x_col], sub[y_col], marker="o", label=str(method))
    plt.xlabel(xlabel)
    plt.ylabel(ylabel)
    plt.title(title)
    plt.grid(True, alpha=0.3)
    plt.legend(frameon=False)
    plt.tight_layout()
    plt.savefig(outpath, dpi=300)
    plt.close()


def plot_placement(table: pd.DataFrame, outpath: Path) -> None:
    pivot = table.pivot_table(index="placement", columns="method", values="RelErr_mean", aggfunc="mean")
    plt.figure(figsize=(8.2, 4.8))
    pivot.plot(kind="bar", ax=plt.gca())
    plt.ylabel("Mean relative recovery error")
    plt.xlabel("Placement strategy")
    plt.title("Real-grid sensor placement effects")
    plt.grid(True, axis="y", alpha=0.3)
    plt.tight_layout()
    plt.savefig(outpath, dpi=300)
    plt.close()


def plot_condition_vs_error(df: pd.DataFrame, outpath: Path) -> None:
    sub = df.replace([np.inf, -np.inf], np.nan).dropna(subset=["kappa_SB", "RelErr"])
    if len(sub) > 3000:
        sub = sub.sample(3000, random_state=123)

    plt.figure(figsize=(7.2, 4.8))
    for method, part in sub.groupby("method"):
        plt.scatter(part["kappa_SB"], part["RelErr"], s=10, alpha=0.45, label=str(method))
    plt.xscale("log")
    plt.yscale("log")
    plt.xlabel(r"Sensed-basis condition number $\kappa(SB)$")
    plt.ylabel("Relative recovery error")
    plt.title("Conditioning versus recovery error on real grid topology")
    plt.grid(True, alpha=0.3)
    plt.legend(frameon=False)
    plt.tight_layout()
    plt.savefig(outpath, dpi=300)
    plt.close()


# ============================================================
# CLI
# ============================================================

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Download real OSM grid data and validate sparse-sensor recovery."
    )
    parser.add_argument("--place", type=str, default="Kampala, Uganda")
    parser.add_argument("--bbox", type=float, nargs=4, default=None,
                        metavar=("NORTH", "WEST", "SOUTH", "EAST"),
                        help="Bounding box. Overrides --place if provided.")
    parser.add_argument("--outdir", type=str, default="real_grid_outputs")
    parser.add_argument("--start_date", type=str, default="2024-01-01")
    parser.add_argument("--end_date", type=str, default="2024-01-21")
    parser.add_argument("--rank", type=int, default=10)
    parser.add_argument("--max_nodes", type=int, default=450)
    parser.add_argument("--n_trials", type=int, default=5)
    parser.add_argument("--seed", type=int, default=123)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    cfg = Config(
        seed=args.seed,
        place=args.place,
        bbox=tuple(args.bbox) if args.bbox is not None else None,
        start_date=args.start_date,
        end_date=args.end_date,
        rank=args.rank,
        max_nodes=args.max_nodes,
        n_trials=args.n_trials,
    )

    outdir = Path(args.outdir)
    safe_mkdir(outdir)
    run_validation(cfg, outdir)


if __name__ == "__main__":
    main()